version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: laravel_appV2
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volume:
      -db_data:./www/var
      -
    ports:
      - "3306:3306"

